import { Link, useLocation } from "wouter";
import { ArrowLeft, Search, PhoneCall, Send, Calendar, TrendingUp, CheckSquare } from "lucide-react";
import { PageHeader } from "@rep/components/RepLayout";

function Module({ icon: Icon, step, title, children }: { icon: React.ElementType; step: number; title: string; children: React.ReactNode }) {
  return (
    <div className="bg-card border border-card-border rounded-xl p-5 md:p-6">
      <div className="flex items-start gap-4 mb-4">
        <div className="shrink-0 w-10 h-10 rounded-lg bg-primary/10 grid place-items-center text-primary">
          <Icon size={18} />
        </div>
        <div>
          <div className="text-xs text-muted-foreground uppercase tracking-wide mb-0.5">Module {step}</div>
          <h2 className="font-serif text-lg text-foreground">{title}</h2>
        </div>
      </div>
      {children}
    </div>
  );
}

function Step({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <div className="flex gap-3 mb-4 last:mb-0">
      <div className="shrink-0 w-6 h-6 rounded-full bg-primary text-primary-foreground text-xs font-medium grid place-items-center mt-0.5">{n}</div>
      <div>
        <div className="text-sm font-medium mb-1">{title}</div>
        <div className="text-sm text-muted-foreground leading-relaxed">{children}</div>
      </div>
    </div>
  );
}

function Tip({ children }: { children: React.ReactNode }) {
  return (
    <div className="mt-4 bg-amber-50 border border-amber-200 rounded-lg p-3 text-xs text-amber-800 leading-relaxed">
      <strong>Pro tip:</strong> {children}
    </div>
  );
}

function Rule({ text }: { text: string }) {
  return (
    <li className="flex items-start gap-2 text-sm text-foreground/80">
      <span className="shrink-0 mt-1.5 w-1.5 h-1.5 rounded-full bg-primary" />
      {text}
    </li>
  );
}

export default function TrainingMaterials() {
  const [location] = useLocation();
  const backHref = location.startsWith("/kb") ? "/kb" : "/resources";
  return (
    <div className="p-4 md:p-8 max-w-4xl mx-auto">
      <Link href={backHref} className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-6">
        <ArrowLeft size={14} /> Back
      </Link>

      <PageHeader
        title="Training Materials"
        description="Six modules covering everything from finding leads to hitting your weekly close target."
      />

      <div className="bg-primary text-primary-foreground rounded-xl p-5 mb-6">
        <div className="font-serif text-lg mb-1">Your target: 3 closes a week</div>
        <p className="text-sm text-primary-foreground/80 leading-relaxed">
          3 closes × $149 closing bonus = <strong>$447 in bonuses this week alone</strong>, before hourly and add-ons. Hit that every week for a month and you've added over $1,700 in bonuses. All leads are provided — <strong>every lead in the Available Leads queue is yours to open</strong>. You don't need to source anything yourself. Your job is to work the queue, send previews, and close.
        </p>
      </div>

      <div className="space-y-4">

        <Module icon={Search} step={1} title="Finding Leads">
          <Step n={1} title="Use the Available Leads queue first">
            The dashboard has a curated list of leads generated by the marketing team — these are warm, sourced from practitioner directories, licensing boards, and inbound site traffic. Open as many as you can work — there's no daily cap. These should be your first call list every morning.
          </Step>
          <Step n={2} title="Psychology Today directory (free)">
            Go to psychologytoday.com/us/therapists/texas. Filter by city. Every practitioner listed there is a live prospect. Cross-reference with Google to see if they have their own site. Practitioners with only a PT profile and no independent site are your warmest audience.
          </Step>
          <Step n={3} title="Texas licensing board lookups">
            The Texas State Board of Examiners of Professional Counselors (tsbep.texas.gov) and BHEC (hhs.texas.gov/bhec) publish licensee search tools. Licensed LPCs, LCSWs, and LMFTs who don't appear on directory searches are gold.
          </Step>
          <Step n={4} title="LinkedIn">
            Search "Licensed Professional Counselor Texas" or "therapist private practice Austin / Dallas / Houston." Filter for recent activity. A practitioner who just updated their LinkedIn profile is often in a phase of growth — perfect timing.
          </Step>
          <Tip>
            The best time to call is Tuesday–Thursday, 9–11am and 1–3pm. Monday mornings and Friday afternoons have the lowest pickup rates. Avoid calling during the noon hour — practitioners often have clients then.
          </Tip>
        </Module>

        <Module icon={PhoneCall} step={2} title="Qualifying a Prospect (First 2 Minutes)">
          <p className="text-sm text-muted-foreground mb-4">Before you spend time on a full pitch, run through this quick mental checklist. If they fail more than 2, politely end the call and move on.</p>
          <div className="space-y-3">
            {[
              { label: "Are they a practicing clinician in Texas?", pass: "Yes — active license", fail: "Retired, other state, or primarily institutional" },
              { label: "Do they see private-pay or sliding-scale clients?", pass: "Yes — they're accessible and cost-sensitive", fail: "Insurance-only and large hospital system" },
              { label: "Do they have or want a web presence?", pass: "Has a directory profile / wants their own site", fail: '"I don\'t want any online presence"' },
              { label: "Are they the decision-maker?", pass: "Solo or practice owner", fail: "Employee who needs partner/employer approval with no timeline" },
              { label: "Do they have 2 minutes?", pass: "Yes or \"call me back at X\"", fail: "Actively dismissive — don't force it, try again later" },
            ].map(({ label, pass, fail }) => (
              <div key={label} className="border border-border rounded-lg p-3 text-sm">
                <div className="font-medium mb-2">{label}</div>
                <div className="grid grid-cols-2 gap-2 text-xs">
                  <div className="bg-emerald-50 text-emerald-700 rounded p-2"><strong>Pass:</strong> {pass}</div>
                  <div className="bg-red-50 text-red-700 rounded p-2"><strong>Fail:</strong> {fail}</div>
                </div>
              </div>
            ))}
          </div>
          <Tip>The goal of qualifying isn't to disqualify — it's to invest your 20 minutes of preview-generation time on the right people. A preview costs you goodwill if you send it to someone who's never going to buy.</Tip>

          <div className="mt-5 border-2 border-amber-300 bg-amber-50 rounded-lg p-4">
            <div className="text-[10px] tracking-[0.18em] uppercase text-amber-800 font-semibold mb-1.5">
              Front-desk / gatekeeper angle
            </div>
            <p className="text-sm text-amber-950 mb-3">
              When the office manager, receptionist, or biller picks up — drop the aesthetics pitch. Their job is throughput. Lead with the four included add-ons (welcome kit, intake forms hub, insurance &amp; sliding-scale badge, Google profile sync) and how they save the front desk ~10 minutes per new patient and cut no-show calls.
            </p>
            <div className="space-y-2 text-xs text-amber-950">
              <div>
                <strong>Discovery question:</strong> "Quick one — who handles new-patient intake right now? You, or does the clinician do it?"
              </div>
              <div>
                <strong>One-liner pitch:</strong> "We give you a $199/mo site that does your front-desk grunt work for you — automatic intake forms, a welcome kit that goes out the second someone books, and your Google listing kept in sync. You stop chasing paperwork."
              </div>
              <div>
                <strong>Objection — "We use [practice management tool] for that":</strong> "Totally — this doesn't replace it. It just stops the patient from showing up unprepared. The forms land in their inbox the moment they book, not when they walk in."
              </div>
              <div>
                <strong>Objection — "I'd have to ask the doctor":</strong> "Of course. Worth knowing first if it would actually save you time though, right? Two minutes — I'll show you the welcome-kit flow, then you can decide if it's worth raising."
              </div>
              <div>
                <strong>Objection — "We don't have a budget":</strong> "It's $199/mo, no setup, cancel anytime. Most offices recover that in saved phone-call minutes by week two. Want me to send you the preview so you can show the doctor the actual numbers?"
              </div>
            </div>
          </div>
        </Module>

        <Module icon={Send} step={3} title="Sending the Preview Link">
          <Step n={1} title="Generate the preview from the lead's profile">
            Go to My Leads → open the lead → click "Generate & send preview." The system uses the practitioner's name, city, and specialty to produce a real personalized mockup. This is not a generic template — it's built from their data.
          </Step>
          <Step n={2} title="Send via SMS (preferred) + email">
            Text converts at a higher rate than email for this audience. Send both if you have the contact info. The message should be short: "Hi [Name] — [Your Name] here from Ashford. Put together a personalized preview of what your site could look like: [link]. Totally free to look at — let me know what you think."
          </Step>
          <Step n={3} title="Follow up 24 hours later">
            If no response, send one follow-up text. If still no response after 48 hours, move the lead to "Nurturing" and make a note to follow up in 7 days.
          </Step>
          <Step n={4} title="Walk them through it live whenever possible">
            The highest close rate comes from screen-share calls where you open the preview together. Ask: "Do you have 5 minutes to look at it together on a quick call?" A live walkthrough lets you address objections in real time.
          </Step>
          <Tip>If a prospect says "It looks nice but I'm not sure," that's a buying signal, not a no. Ask: "What would need to be true for this to be a yes?" The answer tells you exactly what to address.</Tip>
        </Module>

        <Module icon={Calendar} step={4} title="Scheduling Callbacks & Managing Your Pipeline">
          <Step n={1} title="Use the Callbacks page religiously">
            Every lead who says "call me back on X" should be logged in the dashboard the moment you hang up. Don't rely on memory or a notepad. The dashboard sends you reminders. If you miss a callback, you've lost the lead.
          </Step>
          <Step n={2} title="Keep your pipeline in four buckets">
            <div className="mt-2 space-y-2">
              {[
                { bucket: "Hot (contact made, preview sent, follow-up scheduled)", action: "Daily attention — move toward close" },
                { bucket: "Warm (preview sent, no response yet)", action: "48-hour follow-up text" },
                { bucket: "Nurturing (interested but not ready)", action: "7-day touch" },
                { bucket: "Dead (3+ attempts, no response)", action: "Archive — move on" },
              ].map(({ bucket, action }) => (
                <div key={bucket} className="flex gap-2 text-xs">
                  <span className="shrink-0 text-primary font-medium">→</span>
                  <span><strong>{bucket}:</strong> {action}</span>
                </div>
              ))}
            </div>
          </Step>
          <Step n={3} title="Don't let Nurturing become a graveyard">
            If a lead has been in Nurturing for 30+ days with no engagement, archive it. Your time is the most valuable asset here. Fresh leads close faster than stale ones.
          </Step>
          <Tip>Block 8:00–9:00am every weekday for dashboard review: check callbacks, check hot pipeline, plan your call order. Reps who start their day with structure consistently outperform those who just wing it.</Tip>
        </Module>

        <Module icon={TrendingUp} step={5} title="Closing Techniques">
          <Step n={1} title="The assumptive close">
            "Based on what you've told me, Plan B sounds like the right fit — no setup cost, you're live in 48 hours. Want to go ahead and get the onboarding form sent over?"
          </Step>
          <Step n={2} title="The urgency close (honest version)">
            "We cap at 200 clients — we're not there yet, but spots fill up and I can't guarantee your slot if we wait too long. If the site looks right to you, the best move is to get you in the queue now."
          </Step>
          <Step n={3} title="The trial-frame close">
            "There's no annual contract. If it's not working in the first 90 days, you cancel anytime — no notice required. After that, just 30 days written notice. Either way we give you a full content export, so you don't leave empty-handed. The only risk is $199 and 48 hours. The upside is a professional site on a domain you own, compounding in your favor every month."
          </Step>
          <Step n={4} title="The micro-commitment ladder">
            If they're not ready to buy, get a smaller yes: "Can I send you the preview?" → "Can I show you the preview on a quick call?" → "Can I get you set up on the onboarding form?" Each step makes the next one easier.
          </Step>
          <Tip>Silence is your friend after you ask for the close. Don't fill the silence. Let them think. The first person to speak after the close question often loses — if it's you, you're negotiating against yourself.</Tip>
        </Module>

        <Module icon={CheckSquare} step={6} title="Dashboard Guide — Quick Reference">
          <div className="space-y-3 text-sm">
            {[
              { page: "Dashboard", use: "Daily overview — active leads, open callbacks, recent commissions, and key metrics at a glance." },
              { page: "Available Leads", use: "Curated lead list. Open any lead to take it — no daily cap. Opened leads move to My Leads." },
              { page: "My Leads", use: "Your full pipeline. Filter by status (Hot / Warm / Nurturing / Closed / Dead). Open any lead for full detail + action buttons." },
              { page: "Lead Detail", use: "Per-lead hub: contact info, timeline, generate preview, schedule callback, log notes, close the lead." },
              { page: "Callbacks", use: "Every scheduled callback in one place, sorted by date. Don't miss these." },
              { page: "Inbound Queue", use: "Leads who came in through the agency site (filled out the chatbot or contact form). These are warm — respond within 2 hours." },
              { page: "Commission", use: "Your earnings history: closing bonuses, add-on bonuses, and custom dev commissions." },
              { page: "Custom Dev Quotes", use: "If a client needs something outside the standard plan (complex booking, specialty integrations), log it here for a quote. You earn 10% if it closes." },
            ].map(({ page, use }) => (
              <div key={page} className="flex gap-3 border border-border rounded-lg p-3">
                <div className="shrink-0 font-mono text-xs bg-muted px-2 py-1 rounded h-fit">{page}</div>
                <div className="text-xs text-muted-foreground">{use}</div>
              </div>
            ))}
          </div>
        </Module>

        <div className="bg-card border border-card-border rounded-xl p-5">
          <h2 className="font-serif text-lg mb-1">The Perfect Day</h2>
          <p className="text-sm text-muted-foreground mb-4">This is what a winning day looks like. Reps who follow this structure consistently out-earn those who wing it.</p>
          <div className="space-y-3">
            {[
              { time: "8:00–8:30am", title: "Dashboard review", detail: "Check Callbacks for today. Open Available Leads — pick the prospects you want to work today. Review your Hot pipeline for anyone who opened the preview link overnight." },
              { time: "8:30–9:00am", title: "Send morning previews", detail: "Generate and send preview links to anyone you qualified yesterday but haven't sent yet. Best open rates are between 8:30 and 9:30am." },
              { time: "9:00–11:30am", title: "Outbound calling block", detail: "Work through your Available Leads queue. Goal: 30–40 dials. Talk to 4–6 people. Qualify 2–3. Schedule at least 1 callback." },
              { time: "11:30am–12:00pm", title: "Follow-up texts", detail: "One follow-up text to every Warm lead from the last 24 hours. Keep it short: 'Hey [Name], just checking if you got a chance to look at the preview. Happy to walk you through it.' " },
              { time: "1:00–3:00pm", title: "Callback block", detail: "Honor every scheduled callback first — these are your hottest leads. Then do a second dial session on your remaining open leads." },
              { time: "3:00–3:30pm", title: "Pipeline cleanup", detail: "Move won leads to Closed. Move cold leads to Nurturing. Archive dead leads. Log notes. A clean pipeline is a fast pipeline." },
              { time: "3:30–4:00pm", title: "End of day review", detail: "How many previews did you send today? Any callbacks scheduled for tomorrow? Any close you're one objection away from?" },
            ].map(({ time, title, detail }) => (
              <div key={time} className="flex gap-3 border border-border rounded-lg p-3">
                <div className="shrink-0 font-mono text-xs bg-primary/10 text-primary px-2 py-1 rounded h-fit whitespace-nowrap">{time}</div>
                <div>
                  <div className="text-sm font-medium mb-0.5">{title}</div>
                  <div className="text-xs text-muted-foreground leading-relaxed">{detail}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-card border border-card-border rounded-xl p-5">
          <h2 className="font-serif text-lg mb-3">Weekly Success Checklist</h2>
          <ul className="space-y-2">
            {[
              "Opened 10+ leads per day (Mon–Fri = 50 new contacts/week)",
              "Sent at least 10 personalized preview links this week",
              "Followed up on every warm lead within 48 hours",
              "All callbacks logged and honored on time",
              "Archived dead leads to keep pipeline clean",
              "3 closes recorded in the dashboard by Friday",
              "Reviewed commission page to confirm bonuses are logged",
            ].map((item) => (
              <Rule key={item} text={item} />
            ))}
          </ul>
        </div>

      </div>
    </div>
  );
}
